<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Login"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="21.616">
  <properties />
            <testcase name="loginSuccessFunction" time="21.616" classname="cn.jybd.www.testCase.LoginPage_001_LoginSuccessFunction_Test">
                <failure type="java.lang.AssertionError"
                  message="超时!! 20 秒之后还没找到元素 [By.name: body]"
              >
<![CDATA[java.lang.AssertionError: 超时!! 20 秒之后还没找到元素 [By.name: body]
  org.testng.Assert.fail(Assert.java:97)
  cn.jybd.www.util.SeleniumUtil.waitForElementToLoad(SeleniumUtil.java:213)
  cn.jybd.www.pageshelper.HomePageHelper.waitHomePageLoad(HomePageHelper.java:28)
  cn.jybd.www.testCase.LoginPage_001_LoginSuccessFunction_Test.loginSuccessFunction(LoginPage_001_LoginSuccessFunction_Test.java:20)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  org.testng.TestRunner.privateRun(TestRunner.java:763)
  org.testng.TestRunner.run(TestRunner.java:594)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
  org.testng.SuiteRunner.run(SuiteRunner.java:304)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
  org.testng.TestNG.runSuites(TestNG.java:997)
  org.testng.TestNG.run(TestNG.java:965)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
